name: Generar APK de Radiotaxi
on:
  push:
    branches: [ principal ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar Cordova
        run: npm install -g cordova

      - name: Preparar Plataforma Android
        run: |
          cordova platform add android
          
      - name: Compilar APK (Debug)
        run: cordova build android

      - name: Subir APK generado
        uses: actions/upload-artifact@v3
        with:
          name: radiotaxi-apk
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
